name: Code Climate Test Reporter
description: A Buildkite plugin to report coverage with the Code Climate test reporter
author: https://github.com/jobready
requirements: []
configuration:
  properties:
    artifact:
      type: string
    input_type:
      type: string
    prefix:
      type: string
    version:
      type: string
    parts:
      type: integer
    debug:
      type: string
    format:
      type: boolean
    report:
      type: boolean
    file_prefix:
      type: string
    add_prefix:
      type: string
  required: [artifact, input_type]
